-- ============================================================
-- PASSO 1: Rodar este script no Supabase SQL Editor
-- ============================================================

-- Tabela de usuários do sistema
CREATE TABLE IF NOT EXISTS usuarios (
  id SERIAL PRIMARY KEY,
  usuario TEXT UNIQUE NOT NULL,
  senha_hash TEXT NOT NULL,
  criado_em TIMESTAMPTZ DEFAULT NOW()
);

-- Tabela de credenciais
CREATE TABLE IF NOT EXISTS credenciais (
  id SERIAL PRIMARY KEY,
  crede TEXT UNIQUE NOT NULL,
  usuario TEXT,
  ocupacao TEXT,
  especificacao TEXT,
  empresa TEXT,
  abrangencia TEXT,
  placa TEXT,
  credencial_fisica TEXT,
  politica TEXT,
  secao TEXT,
  setor TEXT,
  departamento TEXT,
  area TEXT,
  divisao TEXT,
  unidade TEXT,
  nucleo TEXT,
  grupo TEXT,
  reserva TEXT DEFAULT 'NAO',
  criado_em TIMESTAMPTZ DEFAULT NOW(),
  atualizado_em TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- PASSO 2: Criar o primeiro usuário admin
-- Senha abaixo é: admin123  (você pode trocar depois)
-- Hash gerado com bcrypt rounds=10
-- Para gerar outro hash: https://bcrypt-generator.com/
-- ============================================================

INSERT INTO usuarios (usuario, senha_hash) VALUES
('admin', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy')
ON CONFLICT DO NOTHING;

-- ============================================================
-- PASSO 3: Importar as credenciais da planilha
-- ============================================================

INSERT INTO credenciais (crede, usuario, ocupacao, especificacao, empresa, abrangencia, placa, credencial_fisica, politica, secao, setor, departamento, area, divisao, unidade, nucleo, grupo, reserva) VALUES
('5050','EDSON FELIX','SUPERVISOR','FATURAMENTO','CSC','SETOR','LQG 9E93','SIM','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','NAO'),
('5381','JULIO AVELADA','FOWA','FOWA','FOWA','FOWA','SRE-2H44','SIM','','','','','','','','','','NAO'),
('5791','VANIA REBECHI','DIRETORA','','','','LUR-5313 / FJI-8543','','TEM','TEM','TEM','TEM','TEM','TEM','TEM','TEM','TEM','NAO'),
('5793','EDGAR LEMOS','CONSULTOR','ATENDIMENTO','PALLAS','SEÇÃO','SRT-8B15','','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','NAO'),
('5795','ALEXANDRE RODRIGUES PARREIRA','SUPERVISOR','CCO','PALLAS','SETOR','LPV-5F37','','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','NAO'),
('5797','THAMIRES DA CUNHA DE LIMA','SUPERVISOR','FLUXO DE CAIXA','PALLAS','SETOR','RVY-4C19 / TDY0D19','','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','NAO'),
('5799','ALAN PEREIRA MODESTO','ASSISTENTE','TESOURARIA','CSC','SEÇÃO','KWJ-8G53','','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','NAO'),
('6687','FERNANDA CAMPOS COSTA DE ASSIS','ANALISTA','CONTÁBIL','CSC','DEPARTAMENTO','LSX-8J67 / KRZ-2569','','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','NAO'),
('7371','ADRIANO - FILHA - AUTORIZADO TA','','','','','SRJ-7D77','','','','','','','','','','','NAO'),
('7373','KAREN WATT','SBT','SBT','','','TTH-3G65','','','','','','','','','','','NAO'),
('7375','VAN MEETING','PALLAS','PALLAS','','','RKI7C36','','','','','','','','','','','NAO'),
('7377','RESERVA','','','','','','','','','','','','','','','','SIM'),
('7379','MAX MAIA','COORDENADOR','ATENDIMENTO OPERACIONAL DE CAMPO','4BTS','SEÇÃO','LQV-9A47','','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','NAO'),
('7390','MARCOS FARIAS','ASSISTENTE','FATURAMENTO','CSC','SETOR','TUQ-0E42/DAI-4764','SIM','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','NAO'),
('7392','RESERVA','','','','','','SIM','','','','','','','','','','SIM'),
('7394','BRUNO CASTRO','DIRETOR','EXECUTIVO','4BTS','UNIDADE','FTV-0C96 / KXH2582','','TEM','TEM','TEM','TEM','TEM','TEM','TEM','TEM','TEM','NAO'),
('7413','RESERVA','','','','','','','','','','','','','','','','SIM'),
('7414','HELIO CONDE DE SIMONE','DIRETOR','JURÍDICO','CSC','DEPARTAMENTO','RJJ-5B56','','TEM','TEM','TEM','TEM','TEM','TEM','TEM','TEM','TEM','NAO'),
('7415','MARIANA PADILHA FROES EYER DE ARAUJO','GERENTE','ENDOMARKETING','CSC','DEPARTAMENTO','LRV-4426/KZA-7C42','','TEM','TEM','TEM','TEM','TEM','TEM','TEM','TEM','TEM','NAO'),
('7417','CRISTIANO UCEDA','GERENTE','ADMINISTRATIVO','CSC','DEPARTAMENTO','RKU-9C59','','TEM','TEM','TEM','TEM','TEM','TEM','TEM','TEM','TEM','NAO'),
('7419','LEANDRO - MOTORISTA - JONATHAS','MOTORISTA','','','','SRV0E90','','','','','','','','','','','NAO'),
('7431','LUIZA LIMA','SUPERVISOR','ADMINISTRATIVO','SEDE-MHS','SETOR','LLK3J18','','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','NAO'),
('7433','THAMIRES KLEIN','ANALISTA','TI','4BTS','SEÇÃO','RIX-2C92','','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','NAO'),
('7435','FABIOLA LAZOSKI DA FONSECA BORDALLO','CONSULTOR','ATENDIMENTO','4BTS','SEÇÃO','KRB-8H22','','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','NAO'),
('7436','THIAGO GOULART BOUÇA','GERENTE','ATENDIMENTO OPERACIONAL DE CAMPO','4BTS','SETOR','KYG-7294','','TEM','TEM','TEM','TEM','TEM','TEM','TEM','TEM','TEM','NAO'),
('7438','HELIO CRUZ','COORDENADOR','ATENDIMENTO OPERACIONAL DE CAMPO','4BTS','SEÇÃO','LRR-9861','','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','NAO'),
('7451','RENATA DOS SANTOS DE ABREU BRAGA','CONSULTOR','ATENDIMENTO','4BTS','SEÇÃO','KYU-1572 / LCL-8066','','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','NAO'),
('7453','JULIANA DA ROCHA SANTOS','SUPERVISOR','COMERCIAL E OPERACIONAL','NESTTRAVEL','DEPARTAMENTO','KWO-9762','','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','NAO'),
('7455','RESERVA','','','','','','','','','','','','','','','','SIM'),
('7457','CORINA BURJACK DUARTE','GERENTE','EXECUTIVA','TORCIDA BRASIL','DEPARTAMENTO','LPC-5132','','TEM','TEM','TEM','TEM','TEM','TEM','TEM','TEM','TEM','NAO'),
('7459','MARCOS PORTELLA SEABRA','GERENTE','CONTÁBIL','CSC','DEPARTAMENTO','LUM-6E01','','TEM','TEM','TEM','TEM','TEM','TEM','TEM','TEM','TEM','NAO'),
('7471','LUCAS CAETANO','FOWA','FOWA','FOWA','FOWA','HLE-2F81','','','','','','','','','','','NAO'),
('7473','RESERVA','','','','','','','','','','','','','','','','SIM'),
('7475','THIAGO ABRAHÃO JEEP - VERME','C-LEVEL','CEO','CSC','GRUPO ÁGUIA','LSC2996 / LMK-6C61','','TEM','TEM','TEM','TEM','TEM','TEM','TEM','TEM','TEM','NAO'),
('7477','ABEL - MOTORISTA - WJA','MOTORISTA','','','','RKP-9E40','','','','','','','','','','','NAO'),
('7479','KAMILLA MARQUES DA SILVA SANTOS','ANALISTA','POS-VENDAS','4BTS','SEÇÃO','','SIM','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','NAO'),
('7550','ALEXANDRO LOPES DE MELO','DIRETOR','EXECUTIVO','PALLAS','UNIDADE','SRQ-1F77','','TEM','TEM','TEM','TEM','TEM','TEM','TEM','TEM','TEM','NAO'),
('7552','RESERVA','','','','','','','','','','','','','','','','SIM'),
('7554','LUIZ ALBERTO COLIMERIO','SUPERVISOR','TESOURARIA','PALLAS','SETOR','KUU-5B84','','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','NAO'),
('7570','THIAGO ABRAHÃO','C-LEVEL','CEO','CSC','GRUPO ÁGUIA','SRP-7I57','','TEM','TEM','TEM','TEM','TEM','TEM','TEM','TEM','TEM','NAO'),
('7572','MARLON - MOTORISTA THIAGO','MOTORISTA','','','','RKH-0D06/FKO-7E42','','','','','','','','','','','NAO'),
('7574','CAROLINA POVOA DE ARAGAO','CONSULTOR','RODOVIÁRIO','PALLAS','SETOR','RIV-2G76','','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','NAO'),
('7576','ISABELLA CERQUEIRA DA SILVA MATHIAS','ASSISTENTE','POS-VENDAS','PALLAS','SEÇÃO','LUL-5I52','','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','NAO'),
('7578','LUANE BRUNO DA SILVA','CONSULTOR','ATENDIMENTO','4BTS','SEÇÃO','LUV-0B16','','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','NAO'),
('7590','PATRICIA RIBEIRO VIEGAS','GERENTE','JURÍDICO','PALLAS','DEPARTAMENTO','LUK-3E24/KVM-2390','','TEM','TEM','TEM','TEM','TEM','TEM','TEM','TEM','TEM','NAO'),
('7592','VANDERSON RAMOS DOS SANTOS','SUPERVISOR','TI','CSC','SETOR','LMF-2F66 / RKP-1C25','','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','NAO'),
('7594','RESERVA','','','','','','','','','','','','','','','','SIM'),
('7596','KARINE OLIVEIRA','CONSULTOR','ATENDIMENTO AEREO','PALLAS','SEÇÃO','LVE-7E39','NÃO','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','NAO'),
('7598','RESERVA','','','','','','','','','','','','','','','','SIM'),
('7610','BIANCA FARIA MARQUES TELLES','CONSULTOR','ATENDIMENTO','4BTS','SEÇÃO','TUA-1I40','','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','NAO'),
('7612','ROGERIO PEREIRA DE OLIVEIRA','ASSISTENTE','FATURAMENTO','PALLAS','SETOR','AWV-5152','','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','NAO'),
('7614','AGATHA ABRAHÃO / WALDYR','DIRETOR','EXECUTIVO','SBT','UNIDADE','TTX-4B03','','TEM','TEM','TEM','TEM','TEM','TEM','TEM','TEM','TEM','NAO'),
('7616','LUCIA PAZ','SPORTFIVE -SALA 501','SPORTFIVE -SALA 501','SPORTFIVE','SPORTFIVE -SALA 501','LSV-5935 / CUC-8B12','','','','','','','','','','','NAO'),
('7618','ROBERTO TEIXEIRA HAVELANGE','DIRETOR','COMERCIAL','4BTS','DEPARTAMENTO','KOP-8G72 / HHW-0J51','','TEM','TEM','TEM','TEM','TEM','TEM','TEM','TEM','TEM','NAO'),
('7630','DIEGO PACHECO GONSALVES','ANALISTA','CPD','SEDE-MHS','SEÇÃO','','SIM','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','NAO'),
('7632','BRUNO CASTRO','DIRETOR','EXECUTIVO','4BTS','UNIDADE','FNM-2629 / LMS 5H17','','TEM','TEM','TEM','TEM','TEM','TEM','TEM','TEM','TEM','NAO'),
('7634','LETICIA TURQUES RODRIGUES','CONSULTOR','ATENDIMENTO AEREO','PALLAS','SEÇÃO','RJF5H04','SIM','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','NAO'),
('7636','JONATHAS ABRAHAO','DIRETOR','CORPORATIVO ESPORTIVO','4BTS','UNIDADE','SRV-0C80','','TEM','TEM','TEM','TEM','TEM','TEM','TEM','TEM','TEM','NAO'),
('7638','LEONARDO DE CASTRO VIANA','ANALISTA','FP&A','PALLAS','DEPARTAMENTO','KQS-3768','SIM','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','NAO'),
('7891','EDUARDO ADÃO','GERENTE','ADMINISTRATIVO','CSC','DEPARTAMENTO','KPM-9J51','','TEM','TEM','TEM','TEM','TEM','TEM','TEM','TEM','TEM','NAO'),
('7893','CHARLENE FREITAS LEMOS','CONSULTOR','ATENDIMENTO AEREO','PALLAS','SEÇÃO','','SIM','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','NAO'),
('7895','SERGIO DAMIANI','COORDENADOR','CONTAS A RECEBER/PAGAR','CSC','SETOR','KPD-4209','','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','NAO'),
('7897','LUIS FERNANDO POZZI','SPORTFIVE -SALA 501','SPORTFIVE -SALA 501','SPORTFIVE','SPORTFIVE -SALA 501','SCD-7F58 / LRE-5283','','','','','','','','','','','NAO'),
('7899','VAN','FOWA','','FOWA','','LVE2E29','','','','','','','','','','','NAO'),
('7911','LEANDRO LUIZ DA COSTA','CONSULTOR','ATENDIMENTO AEREO','PALLAS','SEÇÃO','','SIM','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','NAO'),
('7913','CARLOS CHINELLI','DIRETOR','ADMINISTRATIVO FINANCEIRO CONTABIL E FP&A','PALLAS','AREA','SSE-2J04','SIM','TEM','TEM','TEM','TEM','TEM','TEM','TEM','TEM','TEM','NAO'),
('7915','WAGNER ABRAHÃO','CEO DO CONSELHO','','','','SRP-8A02 UEA-1J17','','','','','','','','','','','NAO'),
('7917','PEDRO DE PAOLI ZANDER','SPORTFIVE -SALA 501','SPORTFIVE -SALA 501','SPORTFIVE','SPORTFIVE -SALA 501','LMQ-1E12','','','','','','','','','','','NAO'),
('7919','DIOGO MALTA','GERENTE','RODOVIÁRIO','PALLAS','SETOR','KXE2263/RIY4H98','','TEM','TEM','TEM','TEM','TEM','TEM','TEM','TEM','TEM','NAO'),
('7951','RENATA DE CASTRO ANTUNES','SPORTFIVE -SALA 501','SPORTFIVE -SALA 501','SPORTFIVE','SPORTFIVE -SALA 501','TMC-0I19','','','','','','','','','','','NAO'),
('7953','AGATHA ABRAHÃO / WALDYR','DIRETOR','EXECUTIVO','SBT','UNIDADE','TUM-1J98','','TEM','TEM','TEM','TEM','TEM','TEM','TEM','TEM','TEM','NAO'),
('7955','RESERVA','','','','','','','','','','','','','','','','SIM'),
('7957','RESERVA','','','','','','','','','','','','','','','','SIM'),
('7959','RESERVA','','','','','','','','','','','','','','','','SIM'),
('7971','RESERVA','','','','','','','','','','','','','','','','SIM'),
('7973','SEBASTIÃO FABIO DA SILVA','SUPERVISOR','AÉREO','PALLAS','SETOR','LRE--5D28','','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','PODE SER','NAO'),
('7975','PAULO ROQUE DE MELLO CAPINAM','GERENTE','FATURAMENTO','PALLAS','SETOR','KYT6856','','TEM','TEM','TEM','TEM','TEM','TEM','TEM','TEM','TEM','NAO')
ON CONFLICT (crede) DO NOTHING;
